In [1]:
import numpy as np
a=np.array([[1,-5],[2,2],[0,3]])
b=np.array([[3,1,0,4],[-1,0,2,1]])
print(np.dot(a,b))

[[  8   1 -10  -1]
 [  4   2   4  10]
 [ -3   0   6   3]]


In [2]:
a=np.array([5,0,3])
b=np.array([1,1,0])
print(np.dot(a,b))

5


In [3]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.eye(5,4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)

a.reshape(3, 2)

a.flatten()

array([1, 2, 3, 4, 5, 6])

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv('train.csv')
formula_train = pd.read_csv('formula_train.csv')

test = pd.read_csv('test.csv')
formula_test=pd.read_csv('formula_test.csv')

In [3]:
print('Размерноcть данных тренировочного датасета')
print(train.shape, formula_train.shape)

Размерноcть данных тренировочного датасета
(17010, 82) (17010, 88)


In [4]:
print('Размерноcть данных тестового датасета')
print(test.shape, formula_test.shape)

Размерноcть данных тестового датасета
(4253, 81) (4253, 87)


In [5]:
print(train.isna().sum())

number_of_elements       0
mean_atomic_mass         0
wtd_mean_atomic_mass     0
gmean_atomic_mass        0
wtd_gmean_atomic_mass    0
                        ..
range_Valence            0
wtd_range_Valence        0
std_Valence              0
wtd_std_Valence          0
critical_temp            0
Length: 82, dtype: int64


In [6]:
print(formula_train.isna().sum())

H                0
He               0
Li               0
Be               0
B                0
                ..
Po               0
At               0
Rn               0
critical_temp    0
material         0
Length: 88, dtype: int64


In [7]:
print(test.isna().sum())

number_of_elements       0
mean_atomic_mass         0
wtd_mean_atomic_mass     0
gmean_atomic_mass        0
wtd_gmean_atomic_mass    0
                        ..
wtd_entropy_Valence      0
range_Valence            0
wtd_range_Valence        0
std_Valence              0
wtd_std_Valence          0
Length: 81, dtype: int64


In [8]:
print(formula_test.isna().sum())

H           0
He          0
Li          0
Be          0
B           0
           ..
Bi          0
Po          0
At          0
Rn          0
material    0
Length: 87, dtype: int64


In [14]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 82 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   number_of_elements               17010 non-null  int64  
 1   mean_atomic_mass                 17010 non-null  float64
 2   wtd_mean_atomic_mass             17010 non-null  float64
 3   gmean_atomic_mass                17010 non-null  float64
 4   wtd_gmean_atomic_mass            17010 non-null  float64
 5   entropy_atomic_mass              17010 non-null  float64
 6   wtd_entropy_atomic_mass          17010 non-null  float64
 7   range_atomic_mass                17010 non-null  float64
 8   wtd_range_atomic_mass            17010 non-null  float64
 9   std_atomic_mass                  17010 non-null  float64
 10  wtd_std_atomic_mass              17010 non-null  float64
 11  mean_fie                         17010 non-null  float64
 12  wtd_mean_fie      

In [15]:
print(formula_train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 88 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   H              17010 non-null  float64
 1   He             17010 non-null  int64  
 2   Li             17010 non-null  float64
 3   Be             17010 non-null  float64
 4   B              17010 non-null  float64
 5   C              17010 non-null  float64
 6   N              17010 non-null  float64
 7   O              17010 non-null  float64
 8   F              17010 non-null  float64
 9   Ne             17010 non-null  int64  
 10  Na             17010 non-null  float64
 11  Mg             17010 non-null  float64
 12  Al             17010 non-null  float64
 13  Si             17010 non-null  float64
 14  P              17010 non-null  float64
 15  S              17010 non-null  float64
 16  Cl             17010 non-null  float64
 17  Ar             17010 non-null  int64  
 18  K     

In [16]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4253 entries, 0 to 4252
Data columns (total 81 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   number_of_elements               4253 non-null   int64  
 1   mean_atomic_mass                 4253 non-null   float64
 2   wtd_mean_atomic_mass             4253 non-null   float64
 3   gmean_atomic_mass                4253 non-null   float64
 4   wtd_gmean_atomic_mass            4253 non-null   float64
 5   entropy_atomic_mass              4253 non-null   float64
 6   wtd_entropy_atomic_mass          4253 non-null   float64
 7   range_atomic_mass                4253 non-null   float64
 8   wtd_range_atomic_mass            4253 non-null   float64
 9   std_atomic_mass                  4253 non-null   float64
 10  wtd_std_atomic_mass              4253 non-null   float64
 11  mean_fie                         4253 non-null   float64
 12  wtd_mean_fie        

In [17]:
print(formula_test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4253 entries, 0 to 4252
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   H         4253 non-null   float64
 1   He        4253 non-null   int64  
 2   Li        4253 non-null   float64
 3   Be        4253 non-null   float64
 4   B         4253 non-null   float64
 5   C         4253 non-null   float64
 6   N         4253 non-null   float64
 7   O         4253 non-null   float64
 8   F         4253 non-null   float64
 9   Ne        4253 non-null   int64  
 10  Na        4253 non-null   float64
 11  Mg        4253 non-null   float64
 12  Al        4253 non-null   float64
 13  Si        4253 non-null   float64
 14  P         4253 non-null   float64
 15  S         4253 non-null   float64
 16  Cl        4253 non-null   float64
 17  Ar        4253 non-null   int64  
 18  K         4253 non-null   float64
 19  Ca        4253 non-null   float64
 20  Sc        4253 non-null   floa

In [18]:
train.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass  ...  wtd_mean_Valence  gmean_Valence  wtd_gmean_Valence  \
0        51.968828  ...          2.257143       2.213364           2.219783   
1        47.094633  ...          2.257143       1.888175           2.210679   
2        51.968828  ...          2.271429       2.213364           2.232679   
3        51.968828  ...          2.264286       2.213364           2.226222   
4        51.968828  ...          2.242857       2.213364           2.206963   

   entropy_Valence  wtd_entropy_Valence  range_Valence  wtd_range_Valence  \
0         1.368922             1.066221              1           1.085714   
1         1.557113             1.047221              2           1.128571   
2         1.368922             1.029175              1           1.114286   
3         1.368922             1.048834              1           1.100000   
4         1.368922             1.096052              1           1.057143   

   std_Valence  wtd_std_Valence  critical_temp  
0     0.433013         0.437059           29.0  
1     0.632456         0.468606           26.0  
2     0.433013         0.444697           19.0  
3     0.433013         0.440952           22.0  
4     0.433013         0.428809           23.0  

[5 rows x 82 columns]

In [19]:
test.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   5         92.729214             61.051113   
1                   4         64.632217             55.790060   
2                   4         76.444563             65.834647   
3                   4         96.032850             77.279467   
4                   4         96.451652             75.978308   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          73.132787              37.513930             1.449309   
1          48.775792              35.178830             1.139875   
2          59.356672              48.955994             1.199541   
3          69.515930              53.611120             1.159784   
4          69.689342              53.146925             1.158346   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.146919          122.90607              35.741099   
1                 0.931491          122.90607              35.851917   
2                 1.241867          121.32760              22.132267   
3                 1.267452          151.25960              22.543367   
4                 1.259726          152.93481              24.421050   

   std_atomic_mass  ...  mean_Valence  wtd_mean_Valence  gmean_Valence  \
0        47.094633  ...          2.00          2.200000       1.888175   
1        46.059083  ...          2.25          2.264286       2.213364   
2        43.823354  ...          2.25          2.133333       2.213364   
3        59.663892  ...          2.25          2.166667       2.213364   
4        60.166149  ...          2.25          2.116667       2.213364   

   wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0           2.124829         1.557113             1.053346              2   
1           2.226222         1.368922             1.048834              1   
2           2.111100         1.368922             1.354710              1   
3           2.139826         1.368922             1.351681              1   
4           2.096882         1.368922             1.350047              1   

   wtd_range_Valence  std_Valence  wtd_std_Valence  
0           1.114286     0.632456         0.550325  
1           1.100000     0.433013         0.440952  
2           0.266667     0.433013         0.339935  
3           0.333333     0.433013         0.372678  
4           0.316667     0.433013         0.321023  

[5 rows x 81 columns]

In [23]:
formula_train.head()

H  He   Li   Be    B    C    N    O    F  Ne  ...   Pt   Au   Hg   Tl  \
0  0.0   0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0  ...  0.0  0.0  0.0  0.0   
1  0.0   0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0  ...  0.0  0.0  0.0  0.0   
2  0.0   0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0  ...  0.0  0.0  0.0  0.0   
3  0.0   0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0  ...  0.0  0.0  0.0  0.0   
4  0.0   0  0.0  0.0  0.0  0.0  0.0  4.0  0.0   0  ...  0.0  0.0  0.0  0.0   

    Pb   Bi  Po  At  Rn                material  
0  0.0  0.0   0   0   0         Ba0.2La1.8Cu1O4  
1  0.0  0.0   0   0   0  Ba0.1La1.9Ag0.1Cu0.9O4  
2  0.0  0.0   0   0   0         Ba0.1La1.9Cu1O4  
3  0.0  0.0   0   0   0       Ba0.15La1.85Cu1O4  
4  0.0  0.0   0   0   0         Ba0.3La1.7Cu1O4  

[5 rows x 87 columns]

In [9]:
#объединяем таблицы
formula_train = formula_train.drop(columns=['critical_temp'])
train_full = pd.concat([train, formula_train], axis=1)
train_full.drop(columns=['material'], inplace=True)

In [10]:
train_full.shape

(17010, 168)

In [24]:
train_full.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass  ...   Ir   Pt   Au   Hg   Tl   Pb   Bi  Po  At  Rn  
0        51.968828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0   0   0  
1        47.094633  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0   0   0  
2        51.968828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0   0   0  
3        51.968828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0   0   0  
4        51.968828  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0   0   0  

[5 rows x 168 columns]

In [11]:
test_full=pd.concat([test, formula_test],axis=1)
test_full.drop(columns=['material'], inplace=True)

In [12]:
test_full.shape

(4253, 167)

In [13]:
X = train_full.drop(columns=['critical_temp'])
y = train_full['critical_temp']

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(11907, 167) (5103, 167)
(11907,) (5103,)


In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [16]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [17]:
print(model.coef_)
print(model.intercept_)

[ 1.47033906e+00  8.78540852e-01 -1.24278028e+00 -3.85534395e-01
  6.83452899e-01 -1.64137512e+01 -2.53498819e+00  2.11571881e-01
  1.21086680e-01 -5.06367626e-01 -2.09770570e-02 -2.22096246e-01
 -1.54860648e-02  1.92311827e-01  7.14627822e-02 -2.37991733e+01
  6.50760420e+01  4.10019596e-02  1.96716519e-02 -8.21544250e-02
 -1.35502009e-02 -5.12165751e-01  1.90934395e+00  2.37113812e-01
 -1.58847094e+00 -3.61769420e+01  2.30454473e+01  5.80369792e-02
 -8.55337286e-02 -3.67704005e-01  3.20449086e-02 -5.22166772e-03
  4.49506241e-03  1.01065108e-04  3.53756523e-04 -1.45604983e+01
  6.53071425e+00 -9.04377599e-04 -6.55728213e-04  2.50648674e-03
 -2.55710268e-04 -6.11235065e-02  3.94792978e-01  1.18034908e-01
 -4.63366354e-01  1.11248647e+01 -1.86665471e+01 -3.32925484e-01
 -8.63097804e-02  1.18434028e+00 -5.25597873e-01  1.16032926e+00
 -1.81980810e+00 -8.38582521e-01  1.39593054e+00 -1.81203500e+01
  2.03710986e+01 -1.41755199e-01  5.22298448e-01 -8.17706982e-01
  7.68101024e-01 -9.48904

In [18]:
features = test_full.columns

coeff_df = pd.DataFrame(model.coef_,columns=['Coeff'])
coeff_df['features']=features

coeff_df.sort_values(by='Coeff')

Coeff                      features
76 -85.063538           wtd_entropy_Valence
25 -36.176942         entropy_atomic_radius
72 -25.899650              wtd_mean_Valence
15 -23.799173                   entropy_fie
46 -18.666547  wtd_entropy_ElectronAffinity
..        ...                           ...
74  20.802564             wtd_gmean_Valence
26  23.045447     wtd_entropy_atomic_radius
71  23.396754                  mean_Valence
16  65.076042               wtd_entropy_fie
75  81.767707               entropy_Valence

[167 rows x 2 columns]

In [19]:
y_pred = model.predict(X_test)

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

12.601247024634807
786.9654128803461
0.323164955924541


In [21]:
y_pred_test = model.predict(test_full)
y_pred_test = pd.DataFrame(y_pred_test, columns=['critical_temp'])

y_pred_test = y_pred_test.reset_index()

y_pred_test.to_csv('solution.csv', index=False)